'use client';
import Image from 'next/image'; import { useEffect, useState } from 'react'; import { categories, products } from '../content/products'; import { site, waLink } from '../content/site';
const Arrow=()=> <span aria-hidden="true">↗</span>;
function ProductArt({name}:{name:string}){return <div className="product-art" role="img" aria-label={`${name} — foto əlavə ediləcək`}><div className="grain"/><span>FOTO<br/>TODO</span></div>}
export default function Home(){const [filter,setFilter]=useState('Hamısı'); const [ready,setReady]=useState(false); useEffect(()=>{const t=setTimeout(()=>setReady(true),500); return()=>clearTimeout(t)},[]); const shown=filter==='Hamısı'?products:products.filter(p=>p.category===filter);
return <main className={ready?'ready':''}>
 <header><a href="#ana" className="brand"><Image src="/assets/logo.png" width={46} height={46} alt="CA Wood loqosu"/><span>CA<br/><i>WOOD</i></span></a><nav><a href="#kataloq">Kolleksiya</a><a href="#haqqimizda">Haqqımızda</a><a href="#elaqe">Əlaqə</a></nav><a className="header-cta" href={waLink('Salam, CA Wood məhsulları haqqında məlumat almaq istəyirəm.')} target="_blank">WhatsApp <Arrow/></a></header>
 <section id="ana" className="hero"><div className="hero-glow"/><div className="hero-copy"><p className="eyebrow">BAKI · İSTEHSALÇI.AZ</p><h1>Ağacdan sofra<br/><em>və servis</em> qabları.</h1><p className="intro">Təbii materialın istiliyi, məkanınızın zövqünə uyğun hazırlanmış kolleksiya.</p><div className="actions"><a className="button gold" target="_blank" href={waLink('Salam, sifariş üçün kataloqu görmək istəyirəm.')}>WhatsApp-da sifariş et <Arrow/></a><a className="button line" href="#kataloq">Kataloqa bax ↓</a></div></div><div className="hero-object"><div className="hero-ring"/><div className="hero-bowl"><span>CA<br/>WOOD</span></div><p>ƏL İŞİ · TƏBİİ AĞAC</p></div><div className="scroll-note">AŞAĞI KƏŞF EDİN <span>↓</span></div></section>
 <div className="marquee" aria-label="Məhsul kateqoriyaları"><div>{categories.slice(1).concat(categories.slice(1)).map((c,i)=><span key={i}>{c}<b>✦</b></span>)}</div></div>
 <section className="categories wrap"><div className="section-head"><p className="eyebrow dark">KOLLEKSİYA</p><h2>Hər süfrə üçün<br/><em>bir detal.</em></h2><p>Feed və highlight-lardan görünən məhsul istiqamətləri.</p></div><div className="category-rail">{categories.slice(1).map((c,i)=><article key={c} className={'cat c'+i}><div className="cat-shape"/><p>0{i+1}</p><h3>{c}</h3><span>Seçimlərə bax <Arrow/></span></article>)}</div></section>
 <section id="kataloq" className="catalog"><div className="wrap"><div className="catalog-top"><div><p className="eyebrow dark">SEÇİLMİŞ MƏHSULLAR</p><h2>Taxtanın öz dili var.</h2></div><p>Qiymət və mövcudluq üçün birbaşa yazın.</p></div><div className="filters" role="tablist">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} className={filter===c?'active':''}>{c}</button>)}</div><div className="product-grid">{shown.map((p,i)=><article className="product" key={p.id}><ProductArt name={p.name}/><div className="product-info"><p>{p.category}</p><h3>{p.name}</h3><a target="_blank" aria-label={`${p.name} üçün WhatsApp-da soruş`} href={waLink(`Salam, “${p.name}” məhsulu ilə maraqlanıram. Məlumat verə bilərsiniz?`)}>Soruş <Arrow/></a></div></article>)}</div></div></section>
 <section id="haqqimizda" className="business"><div className="business-art"><div className="vertical-grain"/><p>WOOD<br/>FOR<br/>TABLE</p></div><div className="business-copy"><p className="eyebrow">RESTORAN · KAFE · TOPDAN SİFARİŞ</p><h2>Məkanınıza aid<br/><em>bir süfrə.</em></h2><p>Restoran, kafe və topdan sifarişlər üçün sizə uyğun seçimləri WhatsApp-da birlikdə dəqiqləşdirək.</p><a className="text-link" href={waLink('Salam, restoran/kafe üçün məhsullarla maraqlanıram.')} target="_blank">Bizə yazın <Arrow/></a></div></section>
 <section className="proof wrap"><p className="eyebrow dark">CA WOOD</p><div className="proof-grid"><h2>Sadəcə qab deyil,<br/><em>süfrənin ruhu.</em></h2><div><strong>İstehsalçı</strong><span>İSTEHSALÇI.az</span></div><div><strong>Sədərəkdə mağaza</strong><span>Bakı</span></div><div><strong>Hər gün açıq</strong><span>09:00–17:00</span></div></div></section>
 <section className="insta"><div className="wrap insta-heading"><div><p className="eyebrow">GÜNDƏLİK İLHAM</p><h2>CA Wood dünyası.</h2></div><a href={site.instagram} target="_blank">{site.instagramHandle} <Arrow/></a></div><div className="insta-grid">{Array.from({length:6},(_,i)=><a href={site.instagram} target="_blank" key={i} className={'insta-card i'+i} aria-label="CA Wood Instagram səhifəsinə keç"><span>INSTAGRAM<br/>FOTO TODO</span></a>)}</div></section>
 <section id="elaqe" className="contact wrap"><div><p className="eyebrow dark">BİZİ TAPIN</p><h2>Yaxınlaşın,<br/><em>toxunun.</em></h2><a className="button dark" target="_blank" href={waLink('Salam, CA Wood məhsulları haqqında məlumat almaq istəyirəm.')}>WhatsApp-a keç <Arrow/></a></div><address><p><b>Ünvan</b><a href={site.mapUrl} target="_blank">{site.address} <Arrow/></a></p><p><b>İş saatları</b><span>{site.hours}</span></p><p><b>Əlaqə</b><a href={`tel:${site.phone}`}>{site.phone}</a><a href={waLink('Salam, CA Wood məhsulları haqqında məlumat almaq istəyirəm.')} target="_blank">{site.whatsapp} (WhatsApp)</a></p></address></section>
 <footer><a className="brand" href="#ana"><Image src="/assets/logo.png" width={42} height={42} alt="CA Wood loqosu"/><span>CA<br/><i>WOOD</i></span></a><p>© {new Date().getFullYear()} CA Wood. Bütün hüquqlar qorunur.</p><a href={site.instagram} target="_blank">Instagram <Arrow/></a></footer><a className="float-wa" href={waLink('Salam, CA Wood məhsulları haqqında məlumat almaq istəyirəm.')} target="_blank" aria-label="WhatsApp ilə əlaqə">WA</a>
 </main>}
